version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest


    steps:
      - checkout
      - run: gem list
      - run: gem install bundler
      - run: bundle
      - run: cucumber --require features BackEnd/features/busca_cep.feature --format html --out report.html
      - run: ls
      - run: curl -T report.html ftp://files.000webhost.com:21/public_html --user YmV0ZGV0ZXRpcHM6NTIzNjQ1



