version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest


    steps:
      - checkout
      - run: gem list
      - run: gem install bundler
      - run: bundle
      - run: cd  BackEnd
      - run: cucumber --format html --out report.html

